=== Tung-Neo/Lap2/Book.dtd
<!ELEMENT p (#PCDATA)>
<!ELEMENT book (opener, subtitle?, introduction?, (section | part)+)>
        <!ELEMENT opener (title_text)*>
        <!ELEMENT title_text (#PCDATA)>
        <!ELEMENT subtitle (#PCDATA)>
        <!ELEMENT introduction (header, p+) +>
        <!ELEMENT part (header, chapter+)>
        <!ELEMENT section (header, p+)>
        <!ELEMENT header (#PCDATA)>
        <!ELEMENT chapter (chapter_number, chapter_text)>
        <!ELEMENT chapter_number (#PCDATA)>
        <!ELEMENT chapter_text (p+)>
        <!ATTLIST part ID CDATA #REQUIRED>
        <!ENTITY GLAD "Glad you want to hear about me.">

=== Tung-Neo/Lap2/Book.xml
<?xml version="1.0"?>
<!DOCTYPE book SYSTEM "Book.dtd">
<book>
    <opener>
        <title_text>
            All About Me
        </title_text>
    </opener>
    <part ID="p01">
        <header>Wellcome To My Book</header>
        <chapter>
            <chapter_number>Chapter 1</chapter_number>
            <chapter_text>
                <p>&GLAD;</p>
                <p>There's so much to say!</p>
                <p>How about more about me?</p>
            </chapter_text>
        </chapter>
    </part>
</book>
